# This file assumes bosh_exporter based Service Discovery is being used: ./monitor-bosh.yml

# Exporter jobs
- type: replace
  path: /instance_groups/name=prometheus/jobs/-
  value:
    name: elasticsearch_exporter
    release: prometheus
    properties:
      elasticsearch_exporter:
        es:
          uri: "((elasticsearch_uri))"

# Prometheus Alerts
- type: replace
  path: /instance_groups/name=prometheus/jobs/name=elasticsearch_alerts?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/elasticsearch_alerts/*.alerts

# Grafana Dashboards
- type: replace
  path: /instance_groups/name=grafana/jobs/name=elasticsearch_dashboards?/release
  value: prometheus

- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_files/-
  value: /var/vcap/jobs/elasticsearch_dashboards/*.json
