# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources: <%= p('grafana.datasources.delete', []).to_json %>

# list of datasources to insert/update depending
# what's available in the database
datasources: <%= p('grafana.datasources.create', []).to_json %>
